# Generated by Django 4.2.2 on 2023-06-23 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('urbana', 'Urbana'), ('rural', 'Rural')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BarrioCiudadela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero_viviendas', models.PositiveIntegerField()),
                ('numero_parques', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('numero_edificios', models.PositiveIntegerField()),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenamiento.parroquia')),
            ],
        ),
    ]
