# Generated by Django 4.2.2 on 2023-06-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarrioCiudadela',
            new_name='Barrio',
        ),
    ]
